# Generated by Django 5.2.7 on 2025-10-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_interview", "0002_problem_leetcode_id_problem_title_slug_userproblem"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Message"),
                            ("code_change", "Code Change"),
                            ("code_submission", "Code Submission"),
                            ("hint_request", "Hint Request"),
                            ("code_execution", "Code Execution"),
                            ("interview_start", "Interview Start"),
                            ("interview_end", "Interview End"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="ai_interview.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
