# Generated by Django 5.2.7 on 2025-10-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0003_interviewrecording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewRecording',
        ),
    ]
