# Generated by Django 5.2.7 on 2025-10-19 01:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_interview", "0003_interviewrecording"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewrecording",
            options={},
        ),
        migrations.RemoveField(
            model_name="interviewrecording",
            name="content",
        ),
        migrations.RemoveField(
            model_name="interviewrecording",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="interviewrecording",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="interviewrecording",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to="interview_recordings/"
            ),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="duration_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="recording_ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="recording_started_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="screen_recording",
            field=models.FileField(
                blank=True, null=True, upload_to="interview_recordings/"
            ),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="video_file",
            field=models.FileField(
                blank=True, null=True, upload_to="interview_recordings/"
            ),
        ),
        migrations.AlterField(
            model_name="interviewrecording",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recording",
                to="ai_interview.interviewsession",
            ),
        ),
    ]
