# Generated by Django 5.2.7 on 2025-10-19 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0004_delete_interviewrecording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='audio_recording_url',
            field=models.URLField(blank=True, help_text='URL to audio recording in Supabase'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='code_quality_score',
            field=models.FloatField(blank=True, help_text='Code quality score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='communication_score',
            field=models.FloatField(blank=True, help_text='Communication score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='performance_score',
            field=models.FloatField(blank=True, help_text='Overall performance score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='problem_solving_score',
            field=models.FloatField(blank=True, help_text='Problem solving score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='recording_duration',
            field=models.IntegerField(default=0, help_text='Recording duration in seconds'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='screen_recording_url',
            field=models.URLField(blank=True, help_text='URL to screen recording in Supabase'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='video_recording_url',
            field=models.URLField(blank=True, help_text='URL to video recording in Supabase'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself')),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL from Supabase')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('preferred_language', models.CharField(default='python', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_interviews', models.IntegerField(default=0)),
                ('total_problems_solved', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
