# Generated by Django 5.2.7 on 2025-10-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_interview", "0004_alter_interviewrecording_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="function_signature",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="test_cases",
            field=models.JSONField(default=list),
        ),
    ]
