# Generated by Django 5.2.7 on 2025-10-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_interview", "0005_problem_function_signature_problem_test_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="problem_name_request",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
