# Generated by Django 5.2.7 on 2025-10-19 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0005_interviewsession_audio_recording_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='problem_name_request',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='function_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='InterviewRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='interview_recordings/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interview_recordings/')),
                ('screen_recording', models.FileField(blank=True, null=True, upload_to='interview_recordings/')),
                ('recording_started_at', models.DateTimeField(auto_now_add=True)),
                ('recording_ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='ai_interview.interviewsession')),
            ],
        ),
    ]
